Correcting file upload.
platiagro/datasets pull request #64
Opened 2021-07-23 12:14 UTC by dnlcesilva

Changing the read_indo_dataframe function in datasets.py.

2021-08-04 23:28 UTC, fberanizo commented on datasets/datasets.py
> +    )
@dnlcesilva @dfvneto @andreluiz27 
Links úteis sobre o problema no `pd.read_csv`:
- Essa pessoa teve um problema muito parecido: https://github.com/pallets/werkzeug/issues/1344
- Esta também: https://github.com/tiangolo/fastapi/issues/343
- Essa mensagem tem uma solução de contorno: https://github.com/python/cpython/pull/3249#issuecomment-719880320

Resumo da minha análise:
o fastapi/starlette usam [SpooledTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile) para lidar com os arquivos de upload. SpooledTemporaryFile tem uma implementação que mantem uma parte dos arquivos em memória e o restante em disco ([até 1MB em memória para o fastapi](https://github.com/encode/starlette/pull/582/files)). Funciona assim para evitar [encher a memória lendo o arquivo](https://github.com/encode/starlette/issues/579).

No entanto, o SpooledTemporaryFile apesar de parecer, não é um [readable que herda de io.IOBase](https://docs.python.org/3/library/io.html#class-hierarchy). Ele não implementa, por exemplo atributos "readable", "writable", "seekable".
Isso causou `AttributeError: 'SpooledTemporaryFile' object has no attribute 'readable'` durante o `pd.read_csv`.

Há uma issue aberta para implementar melhorias no core do Python e acabar com este problema: https://github.com/python/cpython/pull/3249

Enquanto isso, a solução para manter o `pd.read_csv` é fazer um ["monkey patch"](https://pt.stackoverflow.com/questions/285190/o-que-%C3%A9-monkey-patch) da classe SpooledTemporaryFile, adicionando os atributos que o pd.read_csv usa:

```python
from tempfile import SpooledTemporaryFile


def _readable(self):
    return self._file.readable()


def _writable(self):
    return self._file.writable()


def _seekable(self):
    return self._file.seekable()


SpooledTemporaryFile.readable = _readable
SpooledTemporaryFile.writable = _writable
SpooledTemporaryFile.seekable = _seekable

```

PS: Não necessariamente precisamos fazer o monkey patch. É uma solução de último caso.
A razão em utilizar o `pd.read_csv` é para facilitar a identificação de header e separador. Se tivermos uma forma diferente para resolver isso, podemos implementar.

2021-08-05 23:36 UTC, fberanizo requested changes

2021-08-05 23:36 UTC, fberanizo commented on datasets/datasets.py
> +    pdread = TextIOWrapper(file, encoding=encoding)
@dnlcesilva ainda precisa do TextIOWrapper ? Se pudermos retirar, melhor (não esqueça de tirar o import TextIOWrapper também.

2021-08-05 23:36 UTC, fberanizo commented on tests/test_api.py
> +        #expected = {"filename": "iris.data", "name": "iris.data"}
é melhor remover código-fonte comentado.

2021-08-05 23:36 UTC, fberanizo commented on datasets/datasets.py
> +    )
Este pd.read_csv ainda faz o load do arquivo todo em memória. 
É melhor usar o nrows aqui também e alterar o save_dataset passando o file (e não o df):
https://github.com/platiagro/datasets/blob/7196c01b5c495e0b632bddb793c0f4ed0e9dc142/datasets/datasets.py#L73-L91

2021-08-06 11:13 UTC, dnlcesilva commented on datasets/datasets.py
> +    pdread = TextIOWrapper(file, encoding=encoding)
@fberanizo ainda necessita, se retiro cai naquele problema de codificação do read_csv.

2021-08-06 11:13 UTC, dnlcesilva commented on tests/test_api.py
> +        #expected = {"filename": "iris.data", "name": "iris.data"}
@fberanizo esqueci.

2021-08-06 11:14 UTC, dnlcesilva commented on datasets/datasets.py
> +    )
@fberanizo vou fazer isso!

2021-08-11 18:39 UTC, fberanizo approved these changes
👍

2021-08-11 18:59 UTC, merged