Fixed blank file upload fix PLATIA-2366
platiagro/datasets pull request #74
Opened 2022-03-22 18:00 UTC by alanmsant2

Correção do upload de arquivo vazio (sem conteúdo)

2022-03-22 19:00 UTC, dfvneto requested changes

2022-03-22 19:01 UTC, alanmsant2 commented on datasets/api.py
> +                print(retries)
boa, tinha esquecido

2022-03-22 19:02 UTC, alanmsant2 commented on datasets/api.py
> +@ app.exception_handler(NotFound)
foi o vs code

2022-03-23 13:42 UTC, dfvneto approved these changes

2022-03-23 18:43 UTC, andreluiz27 approved these changes

2022-03-24 13:32 UTC, merged